production:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV["LOTPOOL_DB"] %>
    pool: 5
    username: <%= ENV["LOTPOOL_USER"] %>
    password: <%= ENV["LOTPOOL_SECRET"] %>
    host: <%= ENV["LOTPOOL_HOST"] %>
    port: 5432
